/* V0.31 → V0.39 — camada final de cena, encontros, testes, horror, portas, inventário, mapa e separação Mestre/Jogador. */
(function(){
  const V039={
    ensure(){
      data.campanha=data.campanha||{}; data.campanha.v039=data.campanha.v039||{};
      const v=data.campanha.v039;
      v.cenaAtual=v.cenaAtual||null; v.cenas=Array.isArray(v.cenas)?v.cenas:[];
      v.encontro=v.encontro||null; v.encontros=Array.isArray(v.encontros)?v.encontros:[];
      v.rolagens=Array.isArray(v.rolagens)?v.rolagens:[]; v.horrorLog=Array.isArray(v.horrorLog)?v.horrorLog:[];
      v.portasDetalhadas=v.portasDetalhadas||{}; v.itensSala=v.itensSala||{}; v.modoJogador=true;
      v.schema=9;
    }, save(){saveLocal();}, floor(){return Number(data.campanha.andarAtual)||5;},
    roomName(){const p=selectedPlayer&&window.HotelGame?.ensure()?.posicoes?.[selectedPlayer.id];return p?.sala||'—';},
    esc(s){return esc(String(s??''));},
    addLog(text){if(typeof logAction==='function')logAction(text);},
    sceneForm(){return `<div class="v039-form-grid"><label>Título<input id="v039SceneTitle" class="control-input" placeholder="Ex.: O corredor fica em silêncio"></label><label>Clima<select id="v039SceneMood" class="control-select"><option>Normal</option><option>Tensão</option><option>Terror</option><option>Grande Noite</option><option>Perseguição</option></select></label><label>Andar<select id="v039SceneFloor" class="control-select">${data.andares.map(a=>`<option value="${a.id}" ${a.id===this.floor()?'selected':''}>${a.id}º — ${this.esc(a.nome.replace(/^\d+º Andar — /,''))}</option>`).join('')}</select></label><label class="v039-full">Texto para os jogadores<textarea id="v039SceneText" class="control-input" rows="3" placeholder="O que os jogadores devem ouvir, ver ou perceber?"></textarea></label><div class="v039-actions v039-full"><button class="dice-btn" onclick="V039.createScene()">CRIAR CENA</button><button class="ghost small" onclick="V039.endScene()">ENCERRAR CENA</button></div></div>`;},
    createScene(){this.ensure();const title=$('#v039SceneTitle')?.value.trim(),text=$('#v039SceneText')?.value.trim();if(!title||!text)return toast('Informe título e texto da cena.');const v=data.campanha.v039,scene={id:'sc-'+Date.now(),titulo:title,texto:text,clima:$('#v039SceneMood')?.value||'Normal',andar:Number($('#v039SceneFloor')?.value)||this.floor(),at:Date.now(),ativa:true};if(v.cenaAtual)v.cenaAtual.ativa=false;v.cenas.unshift(scene);v.cenas=v.cenas.slice(0,30);v.cenaAtual=scene;data.campanha.eventoAtual=title+' — '+text;this.addLog(`Cena criada: ${title}.`);this.save();this.refresh();toast('Cena criada e exibida aos jogadores');},
    endScene(){this.ensure();if(!data.campanha.v039.cenaAtual)return toast('Não há cena ativa.');data.campanha.v039.cenaAtual.ativa=false;data.campanha.v039.cenaAtual=null;this.addLog('Cena atual encerrada.');this.save();this.refresh();toast('Cena encerrada');},
    encounterForm(){return `<div class="v039-form-grid"><label>Nome do encontro<input id="v039EncounterTitle" class="control-input" placeholder="Ex.: O Açougueiro surge na cozinha"></label><label>Tipo<select id="v039EncounterType" class="control-select"><option>Combate</option><option>Fuga</option><option>Investigação</option><option>Perseguição</option><option>Horror</option></select></label><label>Andar<select id="v039EncounterFloor" class="control-select">${data.andares.map(a=>`<option value="${a.id}" ${a.id===this.floor()?'selected':''}>${a.id}º</option>`).join('')}</select></label><label>Sala<select id="v039EncounterRoom" class="control-select"><option value="">Todo o andar</option>${getFloorRooms(this.floor()).map(r=>`<option>${this.esc(r)}</option>`).join('')}</select></label><label class="v039-full">Participantes<input id="v039EncounterParticipants" class="control-input" placeholder="Jogadores, assassino ou NPCs"></label><div class="v039-actions v039-full"><button class="dice-btn" onclick="V039.startEncounter()">INICIAR ENCONTRO</button><button class="ghost small" onclick="V039.endEncounter()">ENCERRAR</button></div></div>`;},
    startEncounter(){this.ensure();const title=$('#v039EncounterTitle')?.value.trim(),parts=$('#v039EncounterParticipants')?.value.trim();if(!title)return toast('Informe o nome do encontro.');const v=data.campanha.v039,e={id:'en-'+Date.now(),titulo:title,tipo:$('#v039EncounterType')?.value||'Combate',andar:Number($('#v039EncounterFloor')?.value)||this.floor(),sala:$('#v039EncounterRoom')?.value||'',participantes:parts||'—',at:Date.now(),ativo:true};if(v.encontro)v.encontro.ativo=false;v.encontro=e;v.encontros.unshift(e);v.encontros=v.encontros.slice(0,30);if(e.tipo==='Combate'&&window.GameEngineV070&&!GameEngineV070.currentCombat()?.ativo)GameEngineV070.startCombat();this.addLog(`Encontro iniciado: ${title}.`);this.save();this.refresh();toast('Encontro iniciado');},
    endEncounter(){this.ensure();if(!data.campanha.v039.encontro)return toast('Não há encontro ativo.');data.campanha.v039.encontro.ativo=false;data.campanha.v039.encontro=null;this.addLog('Encontro encerrado.');this.save();this.refresh();toast('Encontro encerrado');},
    roll(){this.ensure();const pid=$('#v039RollPlayer')?.value,skill=$('#v039RollSkill')?.value,dt=Number($('#v039RollDT')?.value)||10,p=data.jogadores.find(x=>x.id===pid);if(!p)return toast('Selecione um jogador.');const sk=(p.pericias||[]).find(x=>x.nome===skill);let attr=sk?.atributo||'INT';if(skill==='Sobrevivência')attr='INT';const bonus=sk?.treinada?5:0,base=Number(p.atributos?.[attr])||0,die=Math.floor(Math.random()*20)+1,total=die+base+bonus,success=total>=dt;const r={id:'r-'+Date.now(),player:p.nome,skill,die,bonus:base+bonus,dt,total,success,at:Date.now()};data.campanha.v039.rolagens.unshift(r);data.campanha.v039.rolagens=data.campanha.v039.rolagens.slice(0,50);this.addLog(`${p.nome}: ${skill} ${total} vs DT ${dt} — ${success?'SUCESSO':'FALHA'}.`);this.save();this.refresh();toast(`${success?'SUCESSO':'FALHA'} — ${total} vs DT ${dt}`);},
    horror(){this.ensure();const pid=$('#v039HorrorPlayer')?.value,type=$('#v039HorrorType')?.value||'Tensão',text=$('#v039HorrorText')?.value.trim(),p=data.jogadores.find(x=>x.id===pid);if(!text)return toast('Descreva o evento de horror.');const h={id:'h-'+Date.now(),tipo,text,player:p?.nome||'Todos',andar:this.floor(),at:Date.now()};data.campanha.v039.horrorLog.unshift(h);data.campanha.v039.horrorLog=data.campanha.v039.horrorLog.slice(0,40);this.addLog(`Horror: ${text}`);this.save();this.refresh();toast('Evento de horror registrado');if(typeof showAlert==='function')showAlert(text);},
    doorState(key){this.ensure();const v=data.campanha.v039;const states=['aberta','fechada','trancada','bloqueada','quebrável','nada'];const cur=v.portasDetalhadas[key]||'aberta';v.portasDetalhadas[key]=states[(states.indexOf(cur)+1)%states.length];this.save();this.refresh();},
    item(){this.ensure();const room=$('#v039ItemRoom')?.value.trim(),name=$('#v039ItemName')?.value.trim(),desc=$('#v039ItemDesc')?.value.trim();if(!room||!name)return toast('Informe sala e item.');const k=`${this.floor()}:${room}`;data.campanha.v039.itensSala[k]=data.campanha.v039.itensSala[k]||[];data.campanha.v039.itensSala[k].push({id:'it-'+Date.now(),nome:name,descricao:desc||'Sem descrição'});this.save();this.refresh();toast('Item colocado na sala');},
    refresh(){if(typeof renderMaster==='function' && $('#masterScreen')?.classList.contains('active')){ /* renderização é chamada pelo wrapper */ } else if(selectedPlayer)renderSheet();this.renderMasterPanel();this.renderPlayerPanel();},
    renderMasterPanel(){const el=$('#v039Master');if(!el||!data)return;this.ensure();const v=data.campanha.v039,c=v.encontro,scene=v.cenaAtual,f=this.floor();const rolls=v.rolagens.slice(0,8).map(r=>`<div class="v039-log"><b>${this.esc(r.player)} • ${this.esc(r.skill)}</b><span>🎲 ${r.die} + ${r.bonus} = <strong>${r.total}</strong> • DT ${r.dt} • ${r.success?'SUCESSO':'FALHA'}</span></div>`).join('')||'<span class="muted">Nenhuma rolagem.</span>';const killer=data.assassinos.filter(k=>Number(k.andar)===f).map(k=>`<span class="v039-threat">☠ ${this.esc(k.nome)} • ${this.esc(k.sala)}</span>`).join('')||'<span class="muted">Nenhuma ameaça detectada no andar.</span>';const roomOpts=getFloorRooms(f).map(r=>`<option>${this.esc(r)}</option>`).join('');const skillOpts=(data.jogadores[0]?.pericias||[]).map(s=>`<option>${this.esc(s.nome)}</option>`).join('');el.innerHTML=`<div class="v039-header"><div><span class="eyebrow">V0.31 → V0.39</span><h2>Central Mestre ↔ Jogador</h2><p>Controle narrativo, cenas, encontros e testes.</p></div><span class="v039-version">V0.39</span></div><div class="v039-tabs"><button class="active" onclick="V039.tab('cena')">🎬 CENA</button><button onclick="V039.tab('encontro')">⚔ ENCONTRO</button><button onclick="V039.tab('teste')">🎲 TESTES</button></div><div id="v039TabCena" class="v039-tab"><div class="v039-current ${scene?'on':''}"><b>${scene?this.esc(scene.titulo):'Nenhuma cena ativa'}</b><small>${scene?this.esc(scene.texto):'Crie uma cena para controlar o que os jogadores percebem.'}</small></div>${this.sceneForm()}<div class="v039-history">${v.cenas.slice(0,5).map(s=>`<span>${this.esc(s.clima)} • ${this.esc(s.titulo)}</span>`).join('')}</div></div><div id="v039TabEncontro" class="v039-tab hidden"><div class="v039-current ${c?'on':''}"><b>${c?this.esc(c.titulo):'Nenhum encontro ativo'}</b><small>${c?this.esc(c.tipo)+' • '+this.esc(c.participantes):'Crie um encontro para registrar combate, fuga ou perseguição.'}</small></div>${this.encounterForm()}</div><div id="v039TabTeste" class="v039-tab hidden"><div class="v039-form-grid"><label>Jogador<select id="v039RollPlayer" class="control-select">${data.jogadores.map(p=>`<option value="${p.id}">${this.esc(p.nome)}</option>`).join('')}</select></label><label>Perícia<select id="v039RollSkill" class="control-select">${skillOpts}</select></label><label>DT<input id="v039RollDT" class="control-input" type="number" min="1" max="50" value="10"></label><div class="v039-actions"><button class="dice-btn" onclick="V039.roll()">🎲 ROLAR TESTE</button></div></div><div class="v039-history">${rolls}</div></div>`;},
    renderPlayerPanel(){const el=$('#v039Player');if(!el||!data||!selectedPlayer)return;this.ensure();const p=selectedPlayer,pos=window.HotelGame?.ensure()?.posicoes?.[p.id]||{andar:5,sala:'501'},f=Number(pos.andar)||5,v=data.campanha.v039,scene=v.cenaAtual,combat=data.campanha.v030.combate,co=data.campanha.v030.condicoes[p.id]||[],event=v.eventoAtivo;const items=(v.itensSala[`${f}:${pos.sala}`]||[]).map(i=>`<div class="v039-item-public"><b>${this.esc(i.nome)}</b><small>${this.esc(i.descricao)}</small></div>`).join('');el.innerHTML=`<div class="v039-player-header"><div><span class="eyebrow">ÁREA DO JOGADOR • SOMENTE LEITURA</span><h2>${this.esc(p.nome)}</h2><p>${f}º Andar — ${this.esc((data.andares.find(a=>Number(a.id)===f)?.nome||'').replace(/^\d+º Andar — /,''))}</p></div><span class="readonly-badge">🔒 VISÃO SOMENTE LEITURA</span></div>${scene?`<div class="v039-scene-public"><span>🎬 CENA</span><b>${this.esc(scene.titulo)}</b><p>${this.esc(scene.texto)}</p></div>`:''}${combat.ativo?`<div class="v039-combat-public"><b>⚔ COMBATE ATIVO</b><span>Turno: ${this.esc(data.jogadores.find(x=>x.id===combat.turno)?.nome||'—')}</span></div>`:''}<div class="v039-player-grid"><div class="v039-public-panel"><div class="subsection-title">📋 SEU ESTADO</div><div class="v039-stats"><span>PV <b>${p.pv}/${p.pvMax}</b></span><span>PE <b>${p.pe}/${p.peMax}</b></span><span>SAN <b>${p.san}/${p.sanMax}</b></span><span>DEF <b>${p.defesa}</b></span></div><div class="v039-condition-public">${co.length?co.map(x=>`<span>● ${this.esc(x)}</span>`).join(''):'Sem condições ativas.'}</div><div class="subsection-title">🎒 ITENS DISPONÍVEIS NA SALA</div>${items||'<small class="muted">Nenhum item visível.</small>'}</div></div>`;},
    tab(name){['Cena','Encontro','Teste'].forEach(x=>$('#v039Tab'+x)?.classList.toggle('hidden',x.toLowerCase()!==name));document.querySelectorAll('.v039-tabs button').forEach(b=>b.classList.toggle('active',b.textContent.toLowerCase().includes(name==='teste'?'test':name)));}
  };
  window.V039=V039;
  const oldMaster=renderMaster,oldSheet=renderSheet;
  renderMaster=function(){oldMaster();V039.ensure();V039.renderMasterPanel();V039.renderPlayerPanel();};
  renderSheet=function(){oldSheet();V039.ensure();V039.renderPlayerPanel();};
  const boot=()=>{if(!data){setTimeout(boot,100);return;}V039.ensure();if($('#masterScreen')){const d=document.createElement('div');d.id='v039Master';d.className='panel v039-master-panel';$('#masterScreen').insertBefore(d,$('#v030Systems'));}if($('#playerSystems')){const d=document.createElement('div');d.id='v039Player';d.className='panel v039-player-panel';$('#playerSystems').after(d);}renderMaster();if(selectedPlayer)renderSheet();};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
