/* V0.61 — UI de regras, combate e investigação. */
(function(){
  function ensure(id,cls,after){let h=$('#'+id);if(!h){h=document.createElement('div');h.id=id;h.className=cls;$(after)?.after(h);}return h;}
  function renderRules(){const host=ensure('rulesV060Panel','panel rules-v060-panel','#conditionsV059Panel');if(!host||!data)return;const playerOpts=data.jogadores.map(p=>`<option value="${p.id}">${esc(p.nome)}</option>`).join('');const targets=[...data.jogadores,...data.monstros,...data.assassinos].map(p=>`<option value="${p.id}">${esc(p.nome)}</option>`).join('');const skills=(data.jogadores[0]?.pericias||[]).map(s=>`<option>${esc(s.nome)}</option>`).join('');host.innerHTML=`<div class="panel-title"><div><span class="icon">⚙</span><div><h2>Motor de Regras • V0.58–V0.60</h2><p>Testes, recursos, progressão de NEX, resistência elemental e resolução de ataque.</p></div></div></div><div class="rules-v060-grid"><section><h3>Progressão</h3>${data.jogadores.map(p=>`<div class="rule-player"><b>${esc(p.nome)} • ${esc(p.classe||'Sem classe')}</b><div><input id="nex-${p.id}" class="control-input" type="number" min="5" max="99" step="1" value="${parseInt(String(p.nex||'5'),10)||5}"><button class="dice-btn" onclick="RuleEngine.setNex('${p.id}',$('#nex-${p.id}').value)">APLICAR NEX</button></div></div>`).join('')}</section><section><h3>Teste de Ataque</h3><div class="rules-form"><label>Atacante<select id="r060Att" class="control-select">${playerOpts}</select></label><label>Alvo<select id="r060Target" class="control-select">${targets}</select></label><label>Perícia<select id="r060Skill" class="control-select">${skills}</select></label><label>Dano<input id="r060Damage" class="control-input" value="1d4"></label></div><button class="dice-btn" onclick="CombatRulesV060.attack($('#r060Att').value,$('#r060Target').value,$('#r060Skill').value,$('#r060Damage').value)">RESOLVER ATAQUE</button></section></div>`;}
  function renderInvestigation(){const host=ensure('investigationV061Panel','panel investigation-v061-panel','#rulesV060Panel');if(host)InvestigationV061.renderMaster();const ph=ensure('investigationV061PlayerPanel','', '#sheetContent');if(ph&&selectedPlayer)InvestigationV061.renderPlayer();}
  const oldMaster=window.renderMaster;if(typeof oldMaster==='function')window.renderMaster=function(){oldMaster.apply(this,arguments);renderRules();renderInvestigation();};
  const oldSheet=window.renderSheet;if(typeof oldSheet==='function')window.renderSheet=function(){oldSheet.apply(this,arguments);renderInvestigation();};
  const boot=()=>{if(!data){setTimeout(boot,100);return;}renderRules();renderInvestigation();};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
